# -*- coding: utf-8 -*-
"""Monte Carlo Simülasyonu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s62gqbaya0G028KwNZ16vWGBwt0OJ0qQ
"""

import numpy as np
import matplotlib.pyplot as plt

# Simülasyon parametreleri
initial_price = 100  # Başlangıç fiyatı
mu = 0.001  # Günlük beklenen getiri (yüzde 0.1)
sigma = 0.02  # Günlük volatilite (yüzde 2)
days = 252  # 1 yıl (işlem günü)
sims = 1000  # Simülasyon sayısı

# Monte Carlo simülasyonu
np.random.seed(42)  # Tekrar edilebilirlik için sabit seed
simulated_prices = np.zeros((sims, days))

for i in range(sims):
    price = initial_price
    for t in range(1, days):
        # Geometrik Brownian motion modelini uygula
        daily_return = np.random.normal(mu, sigma)
        price = price * (1 + daily_return)
        simulated_prices[i, t] = price

# Fiyatları görselleştir
plt.figure(figsize=(10, 6))
plt.plot(simulated_prices.T, color='blue', alpha=0.1)  # Tüm simülasyonları çiz
plt.title("Monte Carlo Simülasyonu ile Hisse Senedi Fiyatı Tahmini")
plt.xlabel("Gün")
plt.ylabel("Hisse Senedi Fiyatı")
plt.show()

# Sonuçları analiz et: Son günün fiyatlarının dağılımı
final_prices = simulated_prices[:, -1]
plt.figure(figsize=(10, 6))
plt.hist(final_prices, bins=50, color='blue', alpha=0.7)
plt.title("Son Günün Hisse Senedi Fiyatları Dağılımı")
plt.xlabel("Fiyat")
plt.ylabel("Frekans")
plt.show()

# Fiyatın belirli bir seviyenin üzerinde olma olasılığı
threshold = 120  # Hisse senedinin 120'yi aşma olasılığı
probability = (final_prices > threshold).mean()
print(f"Fiyatın 120'yi aşma olasılığı: {probability:.2f}")